export default Control;
declare function Control({ type, name, nodeId, portName, label, inputLabel, data, allData, render, step, options, placeholder, inputData, triggerRecalculation, updateNodeConnections, getOptions, setValue, defaultValue, isMonoControl }: {
    type: any;
    name: any;
    nodeId: any;
    portName: any;
    label: any;
    inputLabel: any;
    data: any;
    allData: any;
    render: any;
    step: any;
    options?: any[];
    placeholder: any;
    inputData: any;
    triggerRecalculation: any;
    updateNodeConnections: any;
    getOptions: any;
    setValue: any;
    defaultValue: any;
    isMonoControl: any;
}): any;
